name: Frontend tests

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  tests:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-latest]
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        cd frontend
        python -m pip install --use-feature=2020-resolver --upgrade pip
        pip install --use-feature=2020-resolver -r requirements.txt
        pip install --use-feature=2020-resolver pytest==5.* py-w3c
    - name: Test with pytest
      run: |
        cd frontend
        BACKEND_URL=https://www.research-software.nl/api PYTHONPATH=. pytest --live
